license_id: cc-by
methodology: Composite Indicator
caveats:
dataset_source: INFORM
package_creator: HDX Data Systems Team
private: False
maintainer: fe820406-8445-4543-8551-fb1489e0c38f
owner_org:  e116c55a-d536-4b47-9308-94b1c7457afe
data_update_frequency: 180
notes: The overall INFORM risk index identifies countries at risk from humanitarian crises and disasters that could overwhelm national response capacity. It is made up of three dimensions - hazards and exposure, vulnerability and lack of coping capacity. Over the last ten years (INFORM Risk Index 2016-2025 2nd edition), there has been a general increase in the risk of humanitarian crises at global level. While there has been an improvement in coping capacity, this has been negated by large increases in the number of people exposed to hazards, and to their vulnerability. The development of institutions and infrastructure has helped decrease risks, but this has not kept pace with the increased exposure to natural hazards and conflict, combined with socioeconomic challenges.
