# Collector specific configuration

base_url:
  risk: "https://drmkc.jrc.ec.europa.eu/inform-index/API/InformAPI/"
  severity: "https://api.acaps.org/api/v1/inform-severity-index/%s/?page=1"

dataset_names:
  risk: "inform-risk-index"
  severity: "inform-severity-index"
